__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_swint.yml',
]

output_dir: ./output/rtdetr_swint_6x_coco
